name: Setup Python environment
description: Set up Python environment for the repository
inputs:
  python-version:
    description: "The Python version to set up"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.9"

    - name: Load cache
      uses: actions/cache@v4
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/pyproject.toml') }}

    - name: Install hssm
      if: steps.cache.outputs.cache-hit != 'true'
      run: uv sync --all-extras --dev
      shell: bash
