#!/bin/bash
#SBATCH --job-name=reg-indiv      ## Name of the job.
#SBATCH -A bornstea_lab     ## account to charge
#SBATCH -p standard          ## partition/queue name
#SBATCH --mem=8G
#SBATCH --array=0-3
#SBATCH --mail-type=end               ## send email when the job ends
#SBATCH --mail-user=jungsuy@uci.edu  ## use this email address


# module load python/3.11  # or your env activation
# source ~/envs/hssm/bin/activate
# module load miniconda3
source ~/.bashrc
conda activate hssm


export JAX_PLATFORM_NAME=cpu
# optional: if you want float64 in JAX too
export JAX_ENABLE_X64=true

# This next line just runs the python script

# python3 running_hddm_cv.py ${1} $SLURM_ARRAY_TASK_ID ${2} -1 0
python3 -u hssm-tst-singlesub.py \
  --ssc ${1} \
  --subj ${2} \
  --chain-id $SLURM_ARRAY_TASK_ID \
  --draws 1000 \
  --tune 2000 \
  --target_accept 0.9 \
  --max_treedepth 5 \
  # > output_model_${1}_chain_${SLURM_ARRAY_TASK_ID}.txt
  # --sampler nuts_numpyro \
  # --outdir chains

exit

