name: Publish tagged releases to PyPI

on:
  release:
    types:
      - published

jobs:
  lint_and_typecheck:
    name: Lint and type-check
    uses: ./.github/workflows/linting_and_type_checking.yml

  run_tests:
    name: Run tests
    uses: ./.github/workflows/run_tests.yml

  publish:
    name: Build wheel and publish to test-PyPI, and then PyPI, and publish docs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Setup environment
        uses: ./.github/setup-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build the wheel
        run: uv build

      - name: Publish to test-PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          uv run python -m twine upload --repository testpypi dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv run python -m twine upload dist/*

      - name: Build and publish docs
        run: uv run mkdocs gh-deploy --force
