name: Build docs

on:
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.9"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Run mkdocs
        run: uv run mkdocs gh-deploy --force
