name: Build docs

on:
  workflow_dispatch:

jobs:
  build_docs:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Setup environment
        uses: ./.github/setup-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dev dependencies
        run: uv pip install --system -e ".[dev]"

      - name: Run mkdocs
        run: uv run mkdocs gh-deploy --force
