name: Check notebooks

on:
  pull_request:
  workflow_call:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.head_commit.message, '[skip fast tests]') }}
    env:
      PYTENSOR_FLAGS: "blas__ldflags=-L/usr/lib/x86_64-linux-gnu -lblas -llapack"

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/setup-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Exercise notebooks
        run: |
          uv sync --all-groups && uv run pytest --nbval --nbval-lax --capture=no --dist loadscope docs/
        env:
          PYTENSOR_FLAGS: ${{ env.PYTENSOR_FLAGS }}
