name: Linting and type checking

on:
  pull_request:
  workflow_call:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          $HOME/.cargo/bin/uv --version

      - name: Create virtual environment
        run: |
          $HOME/.cargo/bin/uv venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          $HOME/.cargo/bin/uv pip install -e '.[dev]'

      - name: Run mypy
        run: mypy src/hssm

      - name: Check formatting
        run: ruff format --check .

      - name: Linting
        run: ruff check src/hssm